### ISSUE TITLE
Touchscreen issues

### ISSUE THREAD

**Issue by szedd** [sharebrained/portapack-hackrf#117]
When I try to calibrate the touchscreen, it often seems to be unresponsive. 
When it is working, it only seems to recognize the first two calibration points (upper left and right),
the calilbration fails at the third point or it starts to take screenshots and enter sleep mode before it fails.

The firmware date is August 9th 2017 (Git Commit Hash a335139)

I don't know if it really is a firmware issue or the hardware failed.

**Comment by jboone** [comment]
The touchscreen calibration mode has turned out to be a bit of a mistake. It's very fussy, and only works well when using something pointed, like a stylus. I really need to either disable it, or loosen up the tolerances.

Bear in mind that this is  a resistive touch screen, which is terrible by comparison to modern smartphone capacitive touch devices... I've mostly avoided implementing touch features in the user interface because of how disappointing it is vs. modern expectations.

When you do make it through the calibration process, does touch entry (say in the receiver frequency screen) work as expected, or is that erratic?

**Comment by szedd** [comment]
Touch entry doesn’t work right at all, all it does is taking screenshots and enter sleep mode, I guess it thinks I am touching the upper right of the screen all the time.
I tried using a stylus, that didn’t help either.

**Comment by szedd** [comment]
I took a Video of the problem https://youtu.be/Bje9wAHSIsc
As you can see, it is not responsive when I try to enter a frequency.
In calibration mode it often takes screenshots when I push center or left and it enters sleep mode when i push on the right side.

**Comment by jboone** [comment]
@szedd Hmmm, yeah. I was hoping this would be something we could fix remotely. Please contact me by the e-mail address at the bottom of [my contact page](https://www.sharebrained.com/about/) and we can discuss how to get that hardware fixed.
