### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by ZeroChaos-** [sharebrained/portapack-hackrf#130]
tag something and ship some binaries for your adoring fans please

**Comment by jboone** [comment]
Still working on stabilizing some large changes without bricking hardware en masse. Should be this week.

**Comment by jboone** [comment]
Several reports of the current commit working OK, both here and in the HAVOC fork. Still trying to address the CPLD changes, because not warning/reminding users of a CPLD bitstream change has caused utter chaos and confusion. A mechanism is forthcoming to make it abundantly clear when the CPLD is not the correct version.

**Comment by jboone** [comment]
And by "HAVOC fork", I mean my fork of HAVOC. Furrtek hasn't merged my changes yet.

**Comment by ZeroChaos-** [comment]
bump :-)  how we doing?

**Comment by ZeroChaos-** [comment]
hi

**Comment by ZeroChaos-** [comment]
you know what is better than less releases? more releases.

**Comment by furrtek** [comment]
It's the exact opposite with empty messages ;p

**Comment by furrtek** [comment]
@ZeroChaos- It's the exact opposite with empty messages ;p

**Comment by jboone** [comment]
Release released: https://github.com/sharebrained/portapack-hackrf/releases/tag/20190405

**Comment by ZeroChaos-** [comment]
thanks!
